{
	"version": 1574890038,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/tiledbackground.png",
		"images/bivouac-sheet0.png",
		"images/dundgeon1-sheet0.png",
		"images/dundgeon2-sheet0.png",
		"images/dundgeon3-sheet0.png",
		"images/lock1-sheet0.png",
		"images/dwarf-sheet0.png",
		"images/shoulders-sheet0.png",
		"images/shoulders-sheet1.png",
		"images/shoulders-sheet2.png",
		"images/head-sheet0.png",
		"images/head-sheet1.png",
		"images/head-sheet2.png",
		"images/headchange-sheet0.png",
		"images/block-sheet0.png",
		"images/target-sheet0.png",
		"images/sword-sheet0.png",
		"images/sword-sheet1.png",
		"images/magic-sheet0.png",
		"images/magic-sheet1.png",
		"images/magic-sheet2.png",
		"images/tiledbackground2.png",
		"images/wall-sheet0.png",
		"images/door-sheet0.png",
		"images/green_ooze-sheet0.png",
		"images/oozespawn-sheet0.png",
		"images/firespawn-sheet0.png",
		"images/fire-sheet0.png",
		"images/particles.png",
		"images/particles2.png",
		"images/nagademon-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite-sheet1.png",
		"images/oozespawn2-sheet0.png",
		"images/firespawn2-sheet0.png",
		"images/arrow-sheet0.png",
		"media/masked rider1.m4a",
		"media/masked rider1.ogg",
		"media/masked rider2.m4a",
		"media/masked rider2.ogg",
		"media/noooooo.m4a",
		"media/noooooo.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}